services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    ports:
      - 9229:9229
      - 3000:3000
    command: node --inspect=0.0.0.0:9229 index.js --host 0.0.0.0 --port 3000 --cache cache
